controller_list:
  - name: fake_robot1_controller
    type: $(arg fake_execution_type)
    joints:
      - robot1_shoulder_pan_joint
      - robot1_shoulder_lift_joint
      - robot1_elbow_joint
      - robot1_wrist_1_joint
      - robot1_wrist_2_joint
      - robot1_wrist_3_joint
  - name: fake_gripper1_controller
    type: $(arg fake_execution_type)
    joints:
      - robot1_arm_finger_joint1
initial:  # Define initial robot poses per group
  - group: robot1
    pose: home
  - group: gripper1
    pose: close