robot1_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot1_shoulder_pan_joint
    - robot1_shoulder_lift_joint
    - robot1_elbow_joint
    - robot1_wrist_1_joint
    - robot1_wrist_2_joint
    - robot1_wrist_3_joint
  gains:
    robot1_shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1_shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1_wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1_wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1_wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper1_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robot1_arm_finger_joint1
  gains:
    robot1_arm_finger_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

# Adding gazebo pid control in gazebo ros control
# TO fix this error
# No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/robot1_shoulder_pan_joint
# No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/robot1_shoulder_lift_joint
# No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/robot1_elbow_joint
# No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/robot1_wrist_1_joint
# No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/robot1_wrist_2_joint
# No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/robot1_wrist_3_joint

# gazebo_ros_control:
#   pid_gains:
#     robot1_shoulder_pan_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     robot1_shoulder_lift_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     robot1_elbow_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     robot1_wrist_1_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     robot1_wrist_2_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     robot1_wrist_3_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
